export const ADD_COLUMN = 'ADD_COLUMN';
export const ADD_CARD = 'ADD_CARD';
export const CHANGE_COLUMN_NAME = 'CHANGE_COLUMN_NAME';
export const CHANGE_CARD_NAME = 'CHANGE_CARD_NAME';
export const EDITING_COLUMN = 'EDITING_COLUMN';
export const CHANGE_CARD_DESCRIPTION = 'CHANGE_CARD_DESCRIPTION';