export const ADD_COLUMN = 'ADD_COLUMN';
export const ADD_CARD = 'ADD_CARD';

export const EDITING_COLUMN = 'EDITING_COLUMN';
export const CHANGE_COLUMN_NAME = 'CHANGE_COLUMN_NAME';
export const CHANGE_CARD_NAME = 'CHANGE_CARD_NAME';

export const CHANGE_CARD_DESCRIPTION = 'CHANGE_CARD_DESCRIPTION';

export const COLUMN_DRAG_START = 'COLUMN_DRAG_START';
export const DROP_COLUMN = 'DROP_COLUMN';

export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';

export const ACTIVE_LABEL = 'ACTIVE_LABEL';
export const CHANGE_LABEL = 'CHANGE_LABEL';
export const DELETE_LABEL = 'DELETE_LABEL';
export const CHANGE_COLUMNS_ACTIVE_LABELS = 'CHANGE_COLUMNS_ACTIVE_LABELS';
export const CREATE_LABEL = 'CREATE_LABEL';

export const ADD_CARD_COVER = 'ADD_CARD_COVER';
export const CHANGE_CARD_COVER_TYPE = 'CHANGE_CARD_COVER_TYPE';
export const CLEAR_CARD_COVER = 'CLEAR_CARD_COVER';

export const ADD_CHECK_LIST = 'ADD_CHECK_LIST';
export const CHANGE_CHECK_LIST = 'CHANGE_CHECK_LIST';
export const DELETE_CHECK_LIST = 'DELETE_CHECK_LIST';
export const ADD_CHECK_LIST_ITEM = 'ADD_CHECK_LIST_ITEM';
export const DELETE_CHECK_LIST_ITEM = 'DELETE_CHECK_LIST_ITEM';
export const COMPLETE_CHECK_LIST_ITEM = 'COMPLETE_CHECK_LIST_ITEM';
export const CHANGE_CHECK_LIST_ITEM = 'CHANGE_CHECK_LIST_ITEM';