export const CHANGE_BOARD_NAME = 'CHANGE_BOARD_NAME';
export const BOARD_LIKE = 'BOARD_LIKE';
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const IMAGE_UPLOAD = 'IMAGE_UPLOAD';
export const SELECT_IMAGE = 'SELECT_IMAGE';
export const DELETE_IMAGE = 'DELETE_IMAGE';